### ISSUE TITLE
Binary and npm package name?

### ISSUE THREAD

**Issue by shama** [nwjs/npm-installer#1]
Currently I have the [npm package name](https://github.com/nwjs/npm-installer/blob/master/package.json) as: `nwjs` but we could probably ask for [nw](https://www.npmjs.com/package/nw), if desired, as it appears to be an empty package. Or another name?

I also currently have the binary named `nwjs`. I'm a fan of having the binary name be the same as the package name but it can really be named anything as well.

/cc @rogerwang

**Comment by rogerwang** [comment]
Yeah. Please ask for it. nwjs is also good.

**Comment by shama** [comment]
npm unpublished `nw` because it was an empty package as part of their no squatting policy. Now that the package name is open, I've published `v0.12.0-alpha1` to: https://www.npmjs.com/package/nw

\o/

**Comment by shama** [comment]
@rogerwang Could you enable the https://travis-ci.org/ hook for npm-installer? Thanks!

**Comment by grillorafael** [comment]
The 0.12.0 has some problems with Phaser game engine. Is there a way to install the 0.11.5 version?

**Comment by mrfabbri** [comment]
@grillorafael for the 0.11.5 version you can still use https://www.npmjs.com/package/nodewebkit
