### ISSUE TITLE
Installation script fails behind proxy

### ISSUE THREAD

**Issue by nisargjhaveri** [nwjs/npm-installer#12]
The script `install.js` which runs on installation fails downloading from `http://dl.nwjs.io/v*` behind proxy.

both `$http_proxy` shell variable and `npm config proxy` are set properly.

Probably problem with the `download` package that is being used, which uses a package called `got` which apparently does not support proxy like this.

It would be great if we can fix this. I am ready to assist if I can be useful.

Thanks.

**Comment by nisargjhaveri** [comment]
Also, it seems like npm is not up-to-date with this repo.

**Comment by shama** [comment]
Related issue https://github.com/sindresorhus/got/issues/7

**Comment by shama** [comment]
@nisargjhaveri Could you test if adding the option `proxy: process.env.http_proxy` to `Download` in `scripts/install.js` fixes the issue for you?

**Comment by nisargjhaveri** [comment]
No it doesn't help adding `proxy: process.env.http_proxy` to `new Download()` call along with `extract: true` and other options.

**Comment by shama** [comment]
I don't really have an easy way to tests this. So a PR that fixes this for you would be appreciated. Thanks!
