### ISSUE TITLE
npm logs EBADENGINE with versions 0.81 / 0.80 / 0.79.1

### ISSUE THREAD

**Issue by marccarranza-clorian** [nwjs/npm-installer#120]
### Issue Type

- [YES] Bug Report

- [YES] Successfully reproduced against the latest version of NW.js?

### Current/Missing Behavior
It's a trivial bug but when installing the versions 0.81.0 / 0.80.0 / 0.79.1 which use node v20.7.0 and v20.5.1, npm logs an EBADENGINE error as the engine specified is v20.5.0 (as seen in package-lock).

![imagen](https://github.com/nwjs/npm-installer/assets/136476428/45723ccb-6484-4b3b-a1a6-7dd0603bf4f4)

![imagen](https://github.com/nwjs/npm-installer/assets/136476428/5651ff78-68f9-4d50-a0ae-fbc9311c9370)

### Expected/Proposed Behavior
Update the library engine string to match nw.js version.

### Additional Info

- Operating System: Ubuntu 22.04.3 LTS
- NW.js Version: 0.81.0
- Repro Link:
- Code snippet:
- Crash report:

**Comment by ayushmanchhabra** [comment]
Hello, thanks for the bug report. We are in the process of changing our release workflow. That should fix this issue.
