### ISSUE TITLE
Show proper failure message on error in install.js 

### ISSUE THREAD

**Issue by nisargjhaveri** [nwjs/npm-installer#13]
Currently while installing with `npm install nw`, if some error occurs in `install.js` it shows a single plain-text message and continues silently. In my case, i got "connect ECONNREFUSED". I had to actually look for some error in the output.

This behavior is highly misleading. It would be useful to give proper failure message on such cases.

**Comment by shama** [comment]
What would you consider a "proper failure message?"

**Comment by nisargjhaveri** [comment]
A eye-catching message, probably in red? :P

Also it would be nice if we can tell `npm` that the installation is failed and make it handle like a normal failure.

I know that we try install script while running `nw` of it is not properly installed. This would prevent us from telling letting `npm` handle failure, since we are aware of it and trying to handle afterwards.

This reminds me of one more thing. After installation with `npm`, somehow `package.json` is remaned to `package_backup.json` and when the `install.js` script runs after that, it dies telling `../package.json` not found.

**Comment by shama** [comment]
Consider this, `ECONNREFUSED` is an extremely common error code that tells you exactly what happened: the connection was refused. If you google that error code you'll see how common it is. Which makes searching for a potential solution to the problem much easier for users. I don't want to obfuscate that.

If you have a _specific change_ backed by _specific reasons_ in mind to make the error more clear for users, I'm totally open for a PR.

> This reminds me of one more thing. After installation with npm, somehow package.json is remaned to package_backup.json and when the install.js script runs after that, it dies telling ../package.json not found.

Would you mind opening this in a new issue with an example that reproduces it? Thanks!
