### ISSUE TITLE
CLI arguments are not passed through to NW.js app

### ISSUE THREAD

**Issue by ronny1982** [nwjs/npm-installer#150]
An application based on NW.js no longer receives command line arguments when launched with `nw`.
This is a regression, probably caused by 5c936ed7 and still works with versions ≤ `0.85.0`

**Steps to reproduce:**
1. Open terminal
2. Run `npx nw . --loglevel=verbose`
  The error message `unknown option '--loglevel=verbose'` occurs before the NW.js app is even launched

**Workaround(s):**
- Revert to `0.85.0`

**Comment by ronny1982** [comment]
The fix only allows unknown options, but did not forward them to the app.

**Comment by ayushmanchhabra** [comment]
I won't have a pc on hand for some time. The fix would be to add an argv argument to the run function which ignores the installer cli arguments. Are you able to pass nw.js args via the chromium-args property in package.json?
