### ISSUE TITLE
NW fails to spawn NWJS binary when using workspaces

### ISSUE THREAD

**Issue by ronny1982** [nwjs/npm-installer#157]
## Steps to reproduce
```zsh
mkdir bug-reproduction
cd bug-reproduction
npm init
# <ENTER> through all defaults
npm install nw@0.87.0
npm exec nw
# nw started & nwjs spawned (showing an expected error)
# <CTRL+C>

npm init -w ./nw-app-001
# <ENTER> through all defaults
npm exec nw --workspace nw-app-001
# nw started but failed to spawn nwjs since it is looking up the wrong directory
```

When using the workspace, the path to the `nwjs` executable is not correctly resolved

<img width="969" alt="Screenshot 2024-04-27 at 13 14 11" src="https://github.com/nwjs/npm-installer/assets/27136773/edd99f87-6862-4187-9fc7-d233be5c79d5">

## Workaround

In `./node_modules/nw/src/parse.js` replace the last short-circuiting condition in line 60
```javascript
options.cacheDir = /*Redacted-4-Readability*/ || path.resolve('.', 'node_modules', 'nw');
```
with
```javascript
options.cacheDir = /*Redacted-4-Readability*/ || path.resolve(path.dirname(process.argv[1]), '..', 'nw');
```

Then run `npm exec nw --workspace nw-app-001` again and it should work (spawning nwjs and showing the expected error)

**Comment by ayushmanchhabra** [comment]
How about this instead?

```javascript
options.cacheDir = /*Redacted-4-Readability*/ || path.resolve('__dirname', '..')
```
