### ISSUE TITLE
Missing Community Standards

### ISSUE THREAD

**Issue by Bashamega** [nwjs/npm-installer#199]
Hello:)

It has come to my attention that this repository is missing a defined set of community standards.
The missing community standards are:

1. A license file
2. GitHub issues templates
3. Pull request templates
4. Code of Conduct file
5. Contributing guide
6. Security policy incase of a breach

Best regards.
Adam.

**Comment by ayushmanchhabra** [comment]
@Bashamega Thanks, I'll add these in soon.

**Comment by Bashamega** [comment]
> @Bashamega Thanks, I'll add these in soon. If this is more of a priority for you, feel free to create a pull request.

No thanks :)
