### ISSUE TITLE
Raspberry Pi 5?

### ISSUE THREAD

**Issue by mikecann** [nwjs/npm-installer#218]
Hi, 

Is it possible to get this working with a Raspberry pi 5? When I execute it on device I get execution error.

I think the pi5 is aarch64.

**Comment by ayushmanchhabra** [comment]
NW.js does not officially support Linux ARM. You can try out the community maintained repo:
https://github.com/LeonardLaszlo/nw.js-armv7-binaries

**Comment by mikecann** [comment]
okay thankyou
