### ISSUE TITLE
Postinstall freeze on OSX Yosemite - 10.10.3 

### ISSUE THREAD

**Issue by XPilot** [nwjs/npm-installer#26]
When trying to install nw, the download is is ok but when it is running the post install, the process freezes and nothing happens. Error is below:

> nw@0.12.2 postinstall /Users/radu.paraschiv/_playground/presentation/NW-Presentation/node_modules/nw
> node scripts/install.js

**Comment by shama** [comment]
Hmm could you try `npm cache clean` and `npm i nw` again?

Also which version of `npm -v`? Thanks!

**Comment by XPilot** [comment]
I tried your suggestion, still get the same result.

npm version: 2.5.1
node version: 0.12.7

**Comment by saitonakamura** [comment]
Same story here on Windows
`npm cache clean` didn't help either
Little research shows that the script freezes on `var createBar = require('multimeter')(process);`
Decomposing it into ```var multimeter = require('multimeter');
var createBar = multimeter(process);``` result into successful execute of first line and freeze on second

Node version: 4.4.1
Npm version: 3.8.3

**Comment by conceptualspace** [comment]
it takes it sweet time but eventually does finish when installing nw 0.14.4 on osx 10.11.5, npm 3.8.3

**Comment by Mithgol** [comment]
I believe it happens when the site `dl.nwjs.io` becomes overloaded, especially immediately after every new NW.js release.

**Comment by Mithgol** [comment]
We could eventually eliminate that central point of failure by switching to some P2P-distributed file system such as [IPFS](https://ipfs.io/), especially after [an implementation of IPFS in JavaScript](https://github.com/ipfs/js-ipfs/) is finished in the future.

**Comment by rohan-deshpande** [comment]
Hi, I have a [CLI](https://github.com/rohan-deshpande/northwest) which uses this package and hmm yeah, it's REALLY slow, I've currently been waiting around 20mins and the `postinstall` is still going. 

This wasn't happening a while back when I was building my tool, but it's really frustrating now, any way to improve this? 

I'm using `npm v5.0.2` now

**Comment by rohan-deshpande** [comment]
Hi,I have a CLI which uses this package and hmm yeah, it's REALLY slow, I've currently been waiting around 20mins and the postinstall is still going.

This wasn't happening a while back when I was building my tool, but it's really frustrating now, any way to improve this?

I'm using npm v5.0.2 now and am on Sierra `v10.12`, not sure this has anything to do with the issue though...

**Comment by Mithgol** [comment]
The issue seems to be mostly server-side and indicates that `dl.nwjs.io` is a bit overloaded.

When a version of NW.js is downloaded repeatedly, local caches (such as https://www.npmjs.com/package/install-nw for example) might become helpful, but in other cases only a P2P system might help.

**Comment by acroyear** [comment]
This is August 2020, and I seem to still be having this issue.  macos,  {"node":"14.5.0","npm":"6.14.5"}.  It installed locally (though i don't think that included the sdk), but the global install (I'm using nvm so there's no issue with file ownership) is freezing up.
