### ISSUE TITLE
Publish 0.12.3 release

### ISSUE THREAD

**Issue by twolfson** [nwjs/npm-installer#27]
Sorry for opening this issue so quickly after the recent release. I realize that we are human and shouldn't be rushed. This is mostly for me tracking the progress of the next release.

On Jul 31, `nw.js@0.12.3` was released. I was wondering if we could get a new release of `npm-installer` for that version?

https://groups.google.com/forum/#!msg/nwjs-general/hhXCS4aXGV0/TUQmcu5XDwAJ

For reference, we would like the patches for https://github.com/plaidchat/plaidchat/issues/100 since it looks like `0.12.3` is including `libffmpegsumo.so` now (which Google Chrome/Chromium has stopped bundling yet we need for audio notifications).

**Comment by shama** [comment]
Published! Thanks for the ping!

**Comment by twolfson** [comment]
Awesome, thanks for the fast turnaround =D
