### ISSUE TITLE
Choosing 32bit nw.exe

### ISSUE THREAD

**Issue by matthiasg** [nwjs/npm-installer#28]
How can i choose which architecture of node-webkit to use/download/run ? on my 64bit machine it always defaults to 64bit.

**Comment by shama** [comment]
There isn't a way atm. We should probably add some env variables to override like we do with `NWJS_URLBASE`.

**Comment by gwicksted** [comment]
+1

**Comment by fritx** [comment]
Related: https://github.com/egoist/nwjs/issues/13

**Comment by saitonakamura** [comment]
I suggest using [nw-builder](https://github.com/nwjs/nw-builder) for this purpose

**Comment by ayushmanchhabra** [comment]
https://github.com/nwjs/npm-installer#install-a-specific-architecture
@TheJaredWilcurt I think this can be closed.
