### ISSUE TITLE
0.11.6 is missing

### ISSUE THREAD

**Issue by adam-lynch** [nwjs/npm-installer#3]
I can't install 0.11.6 with the old nodewebkit package or this. I don't want 0.12-alpha (I assume it's not ready).

**Comment by shama** [comment]
Published `v0.11.6` over at [nodewebkit](https://www.npmjs.com/package/nodewebkit). I'll keep publishing `v0.11.x` over there and keep this installer `>= v0.12.x`.

Thanks again Adam for the ping!

**Comment by adam-lynch** [comment]
Thanks.

Cc @4ver

**Comment by 4ver** [comment]
Savage! Fingers crossed- devtools working again for me :smile:
