### ISSUE TITLE
installation fails on debian/jessie

### ISSUE THREAD

**Issue by eriksank** [nwjs/npm-installer#36]
The npm-based `nw` installation fails on debian/jessie:

    $ sudo npm install -g nw
    > nw@0.12.3 postinstall /usr/local/lib/node_modules/nw
    > node scripts/install.js
    sh: 1: node: not found
    npm WARN This failure might be due to the use of legacy binary "node"
    npm WARN For further explanations, please read
    /usr/share/doc/nodejs/README.Debian

It can be fixed using a workaround:

    sudo ln -s /usr/bin/nodejs /usr/bin/node

From there on, the postinstall script will run properly:

    /usr/local/bin/nw -> /usr/local/lib/node_modules/nw/bin/nw
    nw@0.12.3 postinstall /usr/local/lib/node_modules/nw
    node scripts/install.js

In my impression, the post install script should check if either `/usr/bin/node` or `/usr/bin/nodejs` exists and use the version reported as existing. The `nw` installer may assume elsewhere that the node executable has been installed as `node` while this is no longer the case in the Debian distro.

**Comment by shama** [comment]
This is a problem with Debian. The name `node` conflicts with an older package for ham radios. Instead of giving Node.js that name or choosing not to install Node.js by default, for some reason they thought it was a good idea to rename it to `nodejs`.

Considering everything in Node.js land expects that binary to be named `node`, one cannot simply rename the binary. This issue effects every package using Node.js, not just `nw`.

Either Debian shouldn't install Node.js by default, give `node` to Node.js or it's users will have to continue fixing their mistake.

**Comment by viinkumar** [comment]
@eriksank I tried your method for fixing the problem but i got the following error:
> ln: failed to create symbolic link ‘/usr/bin/node’: File exists

and once i tried to install the package using **sudo npm install -g nw** i received the following error;
> npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
/usr/bin/nw -> /usr/lib/node_modules/nw/bin/nw

> nw@0.12.3 postinstall /usr/lib/node_modules/nw
> node scripts/install.js

> Couldn't connect to http://dl.nwjs.io/v0.12.3/nwjs-v0.12.3-linux-arm.tar.gz (404)
npm ERR! Linux 4.1.19-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "nw"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! nw@0.12.3 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nw@0.12.3 postinstall script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the nw package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nw
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls nw
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

Can you help me with any of this.

**Comment by shama** [comment]
> Couldn't connect to http://dl.nwjs.io/v0.12.3/nwjs-v0.12.3-linux-arm.tar.gz (404)

@viinkumar nwjs doesn't have pre-built binaries for `arm`: https://github.com/nwjs/nw.js/issues/1151

**Comment by viinkumar** [comment]
@shama sorry to bother you but can you help me for steps to achieve that and installing **nwjs** I"ll be very thankful to you as I'm new to using **node**.

**Comment by shama** [comment]
@viinkumar The architecture of the computer you're trying to install on is not supported by this installer. I've heard of some people being able to build the binaries themselves for `arm` architectures but I'm not familiar with how, sorry. I would try asking on their support channel: https://gitter.im/nwjs/nw.js

**Comment by viinkumar** [comment]
@shama thanks for your time.
