### ISSUE TITLE
Separate versions for development/production

### ISSUE THREAD

**Issue by artzhuchka** [nwjs/npm-installer#41]
Hello.
I can't figure how could I install "-sdk" version in development environment and non-sdk version in production environment.
Is it possible?

**Comment by Mithgol** [comment]
Manually or programmatically?

Manually you could run `npm install nw@0.14.0-rc3sdk` to get an SDK version, for example. (Use `npm view nw versions` beforehand to list the available versions. Also note that there are no non-SDK versions of `nw` for some alphas, betas and release candidates.)

Programmatically you could write (in JavaScript) some [postinstall script](https://docs.npmjs.com/misc/scripts) that would analyze the environment and then run `npm` (using [`enpeem`](https://www.npmjs.com/package/enpeem), for example) to install the necessary version of `nw`.

**Comment by artzhuchka** [comment]
Manually but with nw as a dependency in package.json. I can't specify the desired version in the command line.
I install it with `npm install --production` / `npm install`. In first case I want to get non-sdk version, in second case I want to get sdk version.

**Comment by Mithgol** [comment]
The section [`devDependencies`](https://docs.npmjs.com/files/package.json#devdependencies) in `package.json` enumerates packages that are installed by `npm install` but not installed by `npm install --production`. It looks like you may try an SDK version of `nw` in `devDependencies` and a normal version in normal `dependencies`. I haven't tried it myself though, and thus I don't actually know whether the package's version from `devDependencies` overrides a different version of the same package encountered in `dependencies` when `npm install` is run without `--production`. And if it does not, then… well, then I won't have any idea what to do next — except that you might write a feature request to the npm's developers (unless there are no previous similar requests).

**Comment by artzhuchka** [comment]
When I add nw both to `dependencies` and `devDependencies` sections it doesn't work. Npm always installs nw from the `dependencies` section.
I think we can check environment variable `npm_config_production` and install non-sdk version if its value is `true`.

**Comment by Mithgol** [comment]
Who's “we”? Would you write a pull request making changes to `scripts/install.js`?

**Comment by artzhuchka** [comment]
My suggestion is to add npm config property `nwjs_build_type` with available values `normal`, `sdk` and `nacl`. `scripts/install.js` will install specified build when `nw` version does not contain '-sdk' suffix. `nwjs_build_type` property will be ignored if nw version contains '-sdk' suffix.
If you agree with such logic I could make a PR.

**Comment by Mithgol** [comment]
I agree.

**Comment by artzhuchka** [comment]
I make a PR #43

**Comment by Mithgol** [comment]
Your pull request is accepted, thanks.

**Comment by Mithgol** [comment]
Version `nw@0.14.3` / `nw@0.14.3-sdk` is the first published package where both flavours include these changes in `scripts/install.js`.

**Comment by JonasT** [comment]
So how do you actually specify this in the `package.json` now? I just ran into the exact same issue, and I still don't know what I'm supposed to do. Specifying different versions in "dependencies" and "devDependencies" get's me the non_SDK version always, and the help text only specifies how to manually install the SDK version...

**Comment by TheJaredWilcurt** [comment]
I use the -sdk in devDeps and then have a custom build script to handle building for dist. Here's an example:

* https://github.com/open-indy/Koa11y/blob/4.0/build-script.js

It's using `nw-builder`, `rcedit`, `fs-extra`, and `7zip-bin`.

For dev it's just `npm install` and `npm start`. Then for dist it's just `npm run build`.

**Comment by artzhookov** [comment]
@JonasT, you could specify type of build by setting environment variable in command line or in `.npmrc`. See https://github.com/nwjs/npm-installer#install-a-specific-build-type-of-nwjs

**Comment by artzhookov** [comment]
And you should specify non-SDK version in `dependencies` section in this case.

**Comment by JonasT** [comment]
@artzhookov I don't understand. How do I use the `package.json` such that `npm install` (without `--production`) installs the SDK version then?

**Comment by TheMaikXX** [comment]
Have anyone tried npm `workspaces` for this particular use case? We also need to have different version of package for `dev` and `prod` environment.
I just stumbled upon the workspaces and thought it might provide a way of defining a `dev` workspace with `dev` version of package while the `prod` workspace will have the `prod` version..
