### ISSUE TITLE
ELIFECYCLE issue on MAC

### ISSUE THREAD

**Issue by webashutosh** [nwjs/npm-installer#42]
*_Trying this command on MAC
*_`sudo npm install -g nw`

*_Getting the below errors - 
*_/usr/local/bin/nw -> /usr/local/lib/node_modules/nw/bin/nw

> nw@0.14.0-1 postinstall /usr/local/lib/node_modules/nw
> node scripts/install.js

connect ECONNREFUSED 107.170.237.181:80

```
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "nw"
npm ERR! node v5.10.1
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE

npm ERR! nw@0.14.0-1 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nw@0.14.0-1 postinstall script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nw package,
npm ERR! not with npm itself.
```

**Comment by shama** [comment]
`ELIFECYCLE` means the script doesn't have permission to run on your machine.

**Comment by jarpsimoes** [comment]
How resolve this issue? I have same problem on Mac.

**Comment by tadeucaldas** [comment]
Did you guys figured it out? I´m having the same problem here!

**Comment by zhouce** [comment]
I have the same problem on Windows, when I use node 5.10.1 and npm 3.8.3 and grunt-nw-builder.

**Comment by codepython** [comment]
also get this issue before use sudo as prefix

**Comment by shama** [comment]
It depends on how you want permissions to be handled on your machine. The short answer is your installing a package without permissions to execute the script `node scripts/install.js`.

I personally never use `sudo` with `npm`. I have all my module folders `chown` to my user and so I don't run into permission problems.

Here are the npm docs for more info on fixing permissions: https://docs.npmjs.com/getting-started/fixing-npm-permissions

**Comment by codepython** [comment]
good suggestion

**Comment by slackjockey** [comment]
seeing this problem in openSUSE Leap 42.2 64-bit as well:
```
$ uname --machine --kernel-name --kernel-version --operating-system
Linux #1 SMP Fri Jun 30 19:01:19 UTC 2017 (b5079b8) x86_64 GNU/Linux
```
```
$ node --version
v6.10.2
```
```
$ npm --version
5.3.0
```

```
$ npm install

> nw@0.24.3-sdk postinstall /home/pilot/Programmadores/clever_machine_studios/butter-sandwich-basic-walkaround/node_modules/nw
> node scripts/install.js

unexpected end of file
npm WARN bsDemo@0.0.1-beta No repository field.
npm WARN bsDemo@0.0.1-beta No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nw@0.24.3-sdk postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nw@0.24.3-sdk postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pilot/.npm/_logs/2017-08-18T22_46_45_624Z-debug.log
```
permissions should not be a problem as I am not doing anything involving elevated privileges of any kind. I'm am just doing a plain `npm install` from within my project's root path.
