### ISSUE TITLE
Forced install on first run.

### ISSUE THREAD

**Issue by agirorn** [nwjs/npm-installer#44]
When [bin/nw](https://github.com/nwjs/npm-installer/blob/master/bin/nw#L50) starts it is trying to find the binary if it can't find it starts downloading the binary. This is so intrusive and not what you expect from starting nw. In my opinion the install should be responsible for installing the binary. And when you run nw and there is some dependency missing the app should just stop and show an error.

**Comment by Mithgol** [comment]
@shama What do you think of this idea of separation of runtime and intallation time?

**Comment by shama** [comment]
I'm indifferent to this issue. I think having it trying to re-install after failing to previously install is convenient but if people would rather it error instead, that's okay with me too.

**Comment by ayushmanchhabra** [comment]
I might be missing some context since this issue is old, please correct me if I have misinterpreted the issue.

Currently if you `npm install nw` or `npm install`, it looks for existing binary and if not present it downloads it. You can execute runtime by calling it in your Node manifest `scripts`:
```json
"scripts": {
  "start": "nw ."
}
```
