### ISSUE TITLE
Allow to install multiple binaries

### ISSUE THREAD

**Issue by silverkorn** [nwjs/npm-installer#47]
Greetings,

Along with some modifications to [nwjs/nw-builder](https://github.com/nwjs/nw-builder), may I suggest to allow multiple binaries residing in the same `node_module`?
A structure following the one with nw-builder like `./nwjs/win32/`, `./nwjs/win64/`, `./nwjs/osx64/`, `./nwjs/linux32/`, etc.

Modifying  [npm-installer/lib/findpath.js](https://github.com/nwjs/npm-installer/blob/master/lib/findpath.js) to something like this could be done (Maybe adjust for a fallback on 32-bit for a 64-bit OS having only the 32-bit version installed)

``` javascript
var fs = require('fs');
var path = require('path');
var bindir = path.resolve(__dirname, '..', 'nwjs');

module.exports = function() {
  var bin = bindir;
  var arch = process.arch;
  var platform = process.platform;
  if (arch === 'ia32') {
    arch = '32';
  } else if (arch === 'x64'){
    arch = '64';
  }
  if (process.platform === 'darwin') {
    platform = 'osx';
    if (fs.existsSync(path.join(bin, platform + arch, 'Contents'))) {
      bin = path.join(bin, platform + arch, 'Contents', 'MacOS', 'nwjs');
    } else {
      bin = path.join(bin, platform + arch, 'nwjs.app', 'Contents', 'MacOS', 'nwjs');
    }
  } else if (process.platform === 'win32') {
    platform = 'win';
    bin = path.join(bin, platform + arch, 'nw.exe');
  } else {
    bin = path.join(bin, platform + arch, 'nw');
  }
  return bin;
}
```

**Why do I suggested this?**

I'm currently on a situation that I have a shared application on a network and the environment is now having both Windows and MacOSX. Doing as suggested could allow us to keep having one unique place for our application and this avoid us to duplicate the procedures, shortcuts & application updates for each platform.

So the main advantages are:
- Possibility to deploy/install for multiple supported platforms from a single installation (All-in-one / portable);
- Allow to avoid duplication of an entire application just due to platform constraint with NW.js binaries;
- Still be compatible with the usual way with one platform at the time for lighter redistribution or any other platform restriction reason.

Thanks!

**Comment by Mithgol** [comment]
It seems like a good idea, though the path should probably use `platform + '-' + arch` instead of `platform + arch` to match the filenames' approach to clarity.

Would you write a pull request?
