### ISSUE TITLE
Problem with postinstall script

### ISSUE THREAD

**Issue by Xisabla** [nwjs/npm-installer#57]
When I try to install nw package I have this error :

![Screen](https://puu.sh/vIeDt/00587133c2.png)

As gist: https://gist.github.com/Xisabla/b0803b338d757ebe753875665ceb278c

Here is the log gist : https://gist.github.com/Xisabla/733676edaed4248c7b503b1033b87be9

I'm running node & npm on raspbian (Linux 8 jessie), I tried updating npm & reinstalling node, nothing changed.

**Comment by Mithgol** [comment]
What's the npm's version? What's the Node's version?

**Comment by Mithgol** [comment]
Could it be the same problem as in #42?

**Comment by Xisabla** [comment]
Npm version is 4.5.0 and Node's 7.10.0

**Comment by Xisabla** [comment]
I even tried in sudo and it changed nothing :/

**Comment by Mithgol** [comment]
Ah, now I get it.

I should have noticed sooner that the nature of this error is clearly different from #42.

We actually see the results of [line 54](https://github.com/nwjs/npm-installer/blob/eeef9772d5514f3fec7dbbfaed2c25da3f48f34e/scripts/install.js#L54) of the script which is reporting a “404 Not Found” error from the network.

However, I could not reproduce this error on my side by merely running `npm install nw@0.22.1` right now.

Could it be that something blocks the `download` module from connecting to the `dl.nwjs.io` on your system? (For example. a proxy-related problem, like in #55.)

As an additional check: what does happen if you try the hyperlinks from the “Download” section of the [v0.22.1-related blog entry](https://nwjs.io/blog/v0.22.1/) manually in a browser?

**Comment by Xisabla** [comment]
Ok I understand, it's due to the ARM architecture.
I'll try the method you are proposing to me :)

**Comment by Mithgol** [comment]
The issue is closed.
