### ISSUE TITLE
Postinstall error

### ISSUE THREAD

**Issue by rekwet** [nwjs/npm-installer#59]
Hi I receive the following error when running sudo npm install nw. Please help.

postinstall: WARN saveError ENOENT: no such file npm WARN enoent ENOENT: no such file or directory, open '/home/rekwet/Documents/package.json'
npm WARN Documents No description
npm WARN Documents No repository field.
npm WARN Documents No README data
npm WARN Documents No license field.

**Comment by rekwet** [comment]
npm 5.3.0
node 8.5.0
ubuntu 16.04

**Comment by shama** [comment]
It looks like you're trying to save the package to a `package.json` but one doesn't exist. Use `npm init` to create one in your current folder.
