### ISSUE TITLE
Local install error

### ISSUE THREAD

**Issue by darkoverlordofdata** [nwjs/npm-installer#6]
I'm on linux mint. When I try the example and install locally as "npm install nw" I get this error:

npm ERR! Error: EACCES, symlink '../nw/bin/nw'
npm ERR!  { [Error: EACCES, symlink '../nw/bin/nw'] errno: 3, code: 'EACCES', path: '../nw/bin/nw' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! System Linux 3.13.0-24-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "nw"
npm ERR! cwd /home/bruce/Git/nw-sample-apps
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path ../nw/bin/nw
npm ERR! code EACCES
npm ERR! errno 3
npm ERR! stack Error: EACCES, symlink '../nw/bin/nw'
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/bruce/Git/nw-sample-apps/npm-debug.log
npm ERR! not ok code 0

**Comment by shama** [comment]
> Please try running this command again as root/Administrator.

Do you have permission to install to the folder you're trying? If not you'll need to `sudo`, change the permissions or install to another place.

**Comment by darkoverlordofdata** [comment]
I'm just following the example in the readme:

1. git clone https://github.com/zcbenz/nw-sample-apps && cd nw-sample-apps
2. npm install nw
3. "node_modules/.bin/nw" file-explorer

It fails on step 2. I'm just doing this in my home directory, so I have permission - step 1 would not have completed otherwise.

**Comment by shama** [comment]
Right but `EACCES` is a permission error. The command
```
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "nw"
```
doesn't have permission to symlink. You'll need to `sudo` or fix the permissions.

**Comment by darkoverlordofdata** [comment]
Then the example fails on step 3
bruce@barsoom ~/Git/nw-sample-apps $ "node_modules/.bin/nw" file-explorer
bash: node_modules/.bin/nw: No such file or directory

When I look in the file explorer, sure enough, it's not in the project folder. Instead, using:
sudo npm install nw
installed it to ~/node_modules/nw.

I was able to get it to install in the project folder by doing it this way:

1. git clone https://github.com/zcbenz/nw-sample-apps && cd nw-sample-apps
2. npm init
3. npm install nw --save
4. "node_modules/.bin/nw" file-explorer

My npm version is 1.3.10

**Comment by shama** [comment]
Ah I see what the problem was now. `nw-sample-apps` doesn't have a `package.json` anymore so npm was installing further up your folder tree.

I've updated the example in the readme. Thanks!
