### ISSUE TITLE
npm install -g nw not working

### ISSUE THREAD

**Issue by Varunram** [nwjs/npm-installer#64]
OS: macOS 10.13.2
`sudo npm install -g nw` spawns an error even after repeated tries.
[2018-01-08T09_28_36_151Z-debug.log](https://github.com/nwjs/npm-installer/files/1611064/2018-01-08T09_28_36_151Z-debug.log)
CLI output:
```
sudo npm install -g nw
/usr/local/bin/nw -> /usr/local/lib/node_modules/nw/bin/nw
> nw@0.27.4 postinstall /usr/local/lib/node_modules/nw
> node scripts/install.js

EACCES: permission denied, mkdir '/usr/local/lib/node_modules/nw/nwjs'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nw@0.27.4 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nw@0.27.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/varunramg/.npm/_logs/2018-01-08T09_28_36_151Z-debug.log
```

**Comment by shama** [comment]
```
EACCES: permission denied, mkdir '/usr/local/lib/node_modules/nw/nwjs'
```

It doesn't have permission to make that folder. I recommend installing node to not require sudo permissions as it usually causes issues like that ^.

https://gist.github.com/isaacs/579814

**Comment by Varunram** [comment]
I found it strange that it didn't have permissions even after the sudo, maybe I'll try the fix to see if it helps. Thanks!

**Comment by OsamaAbbas** [comment]
In linux, using `--unsafe-perm` solves this issue.
`sudo npm install -g nw --unsafe-perm`
