### ISSUE TITLE
update to 0.31.0

### ISSUE THREAD

**Issue by bschmitlin** [nwjs/npm-installer#68]
just a gentle ping that we are 3 versions behind. Thanks!

**Comment by conceptualspace** [comment]
it would be nice if this were automated otherwise this will happen again and again

**Comment by conceptualspace** [comment]
check this out

https://nwjs.io/versions.json

**Comment by conceptualspace** [comment]
im not sure of the best way to do this that doesn't break the continuity between the npm-installer version numbers matching up with nwjs version numbers, but maybe we could preseve it by adding a command line option similar to `nwjs_build_type`

something like: **nwjs_version_override** = latest / stable / lts

then inside *install.js* or wherever you would do something like:

`request('https://nwjs.io/versions.json', { json: true }, (err, res, body) => `
` { let version = body.nwjs_version_override... `

?

**Comment by conceptualspace** [comment]
alternatively you could hook something up to jenkins / gulp to just bang out the releases for you

**Comment by rogerwang** [comment]
done
