### ISSUE TITLE
end of central directory record signature not found

### ISSUE THREAD

**Issue by theDevelopper** [nwjs/npm-installer#72]
When i do `npm i -D nw@0.36.0-sdk` i get the following error most of the time, but not always.
So far i only had this issue with this npm package only and it started with 0.35.2.
Every fourth time or so it seems to work fine.

I am on macOS 10.14.2 but I also have this issue with Windows 10.
npm 6.5.0

```
> nw@0.36.0-sdk postinstall /Users/theDevelopper/Code/timebro-ui/node_modules/nw
> node scripts/install.js

end of central directory record signature not found
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! nw@0.36.0-sdk postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the nw@0.36.0-sdk postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

I attached the complete log of failure:

[2019-02-05T08_07_24_590Z-debug.log](https://github.com/nwjs/npm-installer/files/2831259/2019-02-05T08_07_24_590Z-debug.log)

**Comment by jssuttles** [comment]
I started getting this recently

**Comment by ayushmanchhabra** [comment]
This usually happens when the complete file is not downloaded. After switching to `axios` in `v0.85.0-1`, I stopped having this issue.
