### ISSUE TITLE
`npm start` should not wait for nw.js to finish

### ISSUE THREAD

**Issue by Mithgol** [nwjs/npm-installer#9]
Currently `npm start` seems to wait until nw.js finishes.

It probably should run nw.js as a non-modal child window (as if it were `start "" nw` on Windows or `nw &` on other systems) and finish immediately.

As a workaround it is possible to replace `"start": "nw"` in `package.json` with `"start": "start \"\" nw"` on Windows and `"start": "nw &"` on other systems, but such `package.json` is no longer cross-platform.

**Comment by shama** [comment]
You can `var nwpath = require('nw')` and then spawn the binary detached: https://iojs.org/api/child_process.html#child_process_options_detached or any other preferred way.

**Comment by Mithgol** [comment]
Good idea, thanks.

(However, consider changing the current default behaviour as well.)

**Comment by timmclean** [comment]
I really like the current behaviour (block until exit)!  Maybe this could be implemented as a flag?

**Comment by shama** [comment]
Happy to accept a patch for a flag, thanks!

**Comment by Mithgol** [comment]
Fixed in bb5872b6e158ab94aa03e2b4942d43e4b01b38c7 by providing an example of spawning a detached process.

**Comment by Mithgol** [comment]
(I decided to refrain from changing the current behaviour of `npm start` because it apparently has its fans.)
