### ISSUE TITLE
errors when doing an nw install with latest node.js

### ISSUE THREAD

**Issue by RichardFoss** [nwjs/npm-installer#93]
Hi, I have been using nw for a number of years. I recently updated node.js to 19.3.0 and am wanting to update nw in my projects. When I do the following:
npm install nw@0.72.0-sdk
I get a number of deprecate messages and then a 404 error. I have attached the log file. After starting the command I do see the nodemodules folder being created, but it is later deleted. The first error appearing is this:

3602 verbose stack Error: command failed
3602 verbose stack     at ChildProcess.<anonymous> (/Users/csrf/.nvm/versions/node/v19.3.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)

[2023-02-13T13_27_27_526Z-debug-0.log](https://github.com/nwjs/npm-installer/files/10722662/2023-02-13T13_27_27_526Z-debug-0.log)

**Comment by abhisri1997** [comment]
**### Same case for me also**

539 info run nw@0.73.0 postinstall { code: 1, signal: null }
540 timing reify:rollback:createSparse Completed in 58ms
541 timing reify:rollback:retireShallow Completed in 1ms
542 timing command:install Completed in 9227ms
543 verbose stack Error: command failed
543 verbose stack     at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
543 verbose stack     at ChildProcess.emit (node:events:513:28)
543 verbose stack     at maybeClose (node:internal/child_process:1098:16)
543 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:304:5)
544 verbose pkgid nw@0.73.0
545 verbose cwd /Users/abhi/github/Forecaster
546 verbose Darwin 22.1.0
547 verbose node v19.4.0
548 verbose npm  v9.2.0
549 error code 1
550 error path /Users/abhi/github/Forecaster/node_modules/nw
551 error command failed
552 error command sh -c node scripts/install.js
553 error Response code 404 (Not Found)
554 verbose exit 1
555 timing npm Completed in 9266ms
556 verbose unfinished npm timer reify 1677054808301
557 verbose unfinished npm timer reify:build 1677054815740
558 verbose unfinished npm timer build 1677054815741
559 verbose unfinished npm timer build:deps 1677054815741
560 verbose unfinished npm timer build:run:postinstall 1677054815747
561 verbose unfinished npm timer build:run:postinstall:node_modules/nw 1677054815748
562 verbose code 1
563 error A complete log of this run can be found in:
563 error     /Users/abhi/.npm/_logs/2023-02-22T08_33_28_259Z-debug-0.log

**Comment by rutgerrrrr** [comment]
https://github.com/nwjs/npm-installer/issues/83#issuecomment-1012369206
This workaround seems to work
